meta_product_name: "Indosuez Fundos"
meta_title: "Indosuez Fundos - Monitoramento da industria de fundos brasileiros"
meta_description: "Indosuez fundos é um app de monitoramento diario dos fundos de investimento do mercado brasileiro"
meta_image: "meta_image.png" # should exist in `app/assets/images/`
